server:
  port: 8082

spring:
  data:
    postgres:
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      host: ${SPRING_DATASOURCE_HOST}
      port: ${SPRING_DATASOURCE_PORT}
      database: ${SPRING_DATASOURCE_DB}
#server:
#  port: 8080
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/feedbacks
#    username: postgres
#    password: 6EZHWJ5URS
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
